volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    
    container_name: foodgram_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodgram
      POSTGRES_HOST: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: locked23/foodgram_backend:latest
    container_name: foodgram_backend
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - ../data:/app/data
    expose:
      - "8000"
    restart: always

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    env_file:
      - ../.env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/app/static
      - media:/app/media
      - type: bind
        source: ../frontend/build
        target: /usr/share/nginx/html
    depends_on:
      - backend
    restart: always