volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    
    container_name: foodgram_db
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: locked23/foodgram_backend:latest
    container_name: foodgram_backend
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
       - static:/app/static
       - media:/app/media
    expose:
      - "8000"
    restart: always

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    env_file:
      - ../.env
    ports:
      - "8080:80"
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - static:/app/static
       - media:/app/media
       - type: bind
         source: ../frontend/build
         target: /usr/share/nginx/html
    depends_on:
      - backend
    restart: always