volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    
    container_name: foodgram_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodgram
      POSTGRES_HOST: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    container_name: foodgram_backend
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
      - ../data:/app/data
    expose:
      - "8000"
    restart: always

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    env_file:
      - ../.env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
    restart: always